# Generated by Django 2.2 on 2020-07-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['date_time', 'commentor']},
        ),
    ]
